### ISSUE TITLE
why support lean 3 ?

### ISSUE THREAD

**Issue by Seasawher** [Julian/setup-lean#1]
I don't know what this part means as I don't know lean 3, but why is lean 3 supported?
I thought Lean 3 had been deprecated.

```yml
    - name: Install lean-language-server if Lean 3
      shell: bash
      run: npm install -g lean-language-server
      if: ${{ inputs.lean3ls == 'true' || env.lean3ls == 'true' }}
```
